In [105]:
import numpy as np
import pandas as pd
import scipy as sp
import math
from sklearn import tree
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import classification_report
from sklearn.cross_validation import train_test_split
import csv
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.neighbors import KNeighborsClassifier

In [106]:
csv_data = pd.read_csv("test&train_data.csv")  # 读取训练数据

In [107]:
train_data=csv_data.iloc[0:2100,:]
test_data=csv_data.iloc[2100:3000,:]

In [108]:


t1=train_data.iloc[0:99,:]
t2=train_data.iloc[100:199,:]
t3=train_data.iloc[200:299,:]
t4=train_data.iloc[300:399,:]
t5=train_data.iloc[400:499,:]
t6=train_data.iloc[500:599,:]
t7=train_data.iloc[600:699,:]
t8=train_data.iloc[700:799,:]
t9=train_data.iloc[800:899,:]
t10=train_data.iloc[900:999,:]
t11=train_data.iloc[1000:1099,:]
t12=train_data.iloc[1100:1199,:]
t13=train_data.iloc[1200:1299,:]
t14=train_data.iloc[1300:1399,:]
t15=train_data.iloc[1400:1499,:]
t16=train_data.iloc[1500:1599,:]
t17=train_data.iloc[1600:1699,:]
t18=train_data.iloc[1700:1799,:]
t19=train_data.iloc[1800:1899,:]
t20=train_data.iloc[1900:1999,:]
t21=train_data.iloc[2000:2099,:]


vector1=t1.describe().iloc[[1,2,3,7],:].T.values
vector2=t2.describe().iloc[[1,2,3,7],:].T.values
vector3=t3.describe().iloc[[1,2,3,7],:].T.values
vector4=t4.describe().iloc[[1,2,3,7],:].T.values
vector5=t5.describe().iloc[[1,2,3,7],:].T.values
vector6=t6.describe().iloc[[1,2,3,7],:].T.values
vector7=t7.describe().iloc[[1,2,3,7],:].T.values
vector8=t8.describe().iloc[[1,2,3,7],:].T.values
vector9=t9.describe().iloc[[1,2,3,7],:].T.values
vector10=t10.describe().iloc[[1,2,3,7],:].T.values
vector11=t11.describe().iloc[[1,2,3,7],:].T.values
vector12=t12.describe().iloc[[1,2,3,7],:].T.values
vector13=t13.describe().iloc[[1,2,3,7],:].T.values
vector14=t14.describe().iloc[[1,2,3,7],:].T.values
vector15=t15.describe().iloc[[1,2,3,7],:].T.values
vector16=t16.describe().iloc[[1,2,3,7],:].T.values
vector17=t17.describe().iloc[[1,2,3,7],:].T.values
vector18=t18.describe().iloc[[1,2,3,7],:].T.values
vector19=t19.describe().iloc[[1,2,3,7],:].T.values
vector20=t20.describe().iloc[[1,2,3,7],:].T.values
vector21=t21.describe().iloc[[1,2,3,7],:].T.values
x1=np.vstack((vector1,vector2))
x2=np.vstack((x1,vector3))
x3=np.vstack((x2,vector4))
x4=np.vstack((x3,vector5))
x5=np.vstack((x4,vector6))
x6=np.vstack((x5,vector7))
x7=np.vstack((x6,vector8))
x8=np.vstack((x7,vector9))
x9=np.vstack((x8,vector10))
x10=np.vstack((x9,vector11))
x11=np.vstack((x10,vector12))
x12=np.vstack((x11,vector13))
x13=np.vstack((x12,vector14))
x14=np.vstack((x13,vector15))
x15=np.vstack((x14,vector16))
x16=np.vstack((x15,vector17))
x17=np.vstack((x16,vector18))
x18=np.vstack((x17,vector19))
x19=np.vstack((x18,vector20))
train_vectors=np.vstack((x19,vector21))

y=list(range(0,21))*21
train_catagory=np.array(y)

In [109]:
t_vector1=test_data.iloc[0:99,:].describe().iloc[[1,2,3,7],:].T.values
t_vector2=test_data.iloc[100:199,:].describe().iloc[[1,2,3,7],:].T.values
t_vector3=test_data.iloc[200:299,:].describe().iloc[[1,2,3,7],:].T.values
t_vector4=test_data.iloc[300:399,:].describe().iloc[[1,2,3,7],:].T.values
t_vector5=test_data.iloc[400:499,:].describe().iloc[[1,2,3,7],:].T.values
t_vector6=test_data.iloc[500:599,:].describe().iloc[[1,2,3,7],:].T.values
t_vector7=test_data.iloc[600:699,:].describe().iloc[[1,2,3,7],:].T.values
t_vector8=test_data.iloc[700:799,:].describe().iloc[[1,2,3,7],:].T.values
t_vector9=test_data.iloc[800:899,:].describe().iloc[[1,2,3,7],:].T.values



x1=np.vstack((t_vector1,t_vector2))
x2=np.vstack((x1,t_vector3))
x3=np.vstack((x2,t_vector4))
x4=np.vstack((x3,t_vector5))
x5=np.vstack((x4,t_vector6))
x6=np.vstack((x5,t_vector7))
x7=np.vstack((x6,t_vector8))

test_vectors=np.vstack((x7,t_vector9))

y=list(range(0,21))*9
test_catagory=np.array(y)

In [110]:
cross_validation_vector=np.vstack((train_vectors,test_vectors))
cross_validation_catagory=np.array(list(range(0,21))*20+list(range(0,21))*10)

In [111]:
train_vectors

array([[-24.65656566,   3.32940399, -32.        , -18.        ],
       [-38.47474747,   2.55687722, -44.        , -34.        ],
       [-38.76767677,   0.75360742, -41.        , -37.        ],
       ...,
       [-57.24242424,   4.05344628, -64.        , -50.        ],
       [-54.45454545,   1.02292824, -62.        , -53.        ],
       [-56.50505051,   2.62007064, -79.        , -55.        ]])

In [112]:
errors=[]
per_errors=[]
for k in range(2,30):
    f=KNeighborsClassifier(n_neighbors=k)
    f.fit(train_vectors,train_catagory)
    prediction=f.predict(test_vectors)
    distance_error=sum(abs(prediction-test_catagory)*0.5)/189
    per_distance_error=sum(   np.true_divide(abs(prediction-test_catagory),test_catagory+0.00000001)   )   /    189
    errors.append(distance_error)
    per_errors.append(per_distance_error)

In [113]:
train_vectors

array([[-24.65656566,   3.32940399, -32.        , -18.        ],
       [-38.47474747,   2.55687722, -44.        , -34.        ],
       [-38.76767677,   0.75360742, -41.        , -37.        ],
       ...,
       [-57.24242424,   4.05344628, -64.        , -50.        ],
       [-54.45454545,   1.02292824, -62.        , -53.        ],
       [-56.50505051,   2.62007064, -79.        , -55.        ]])

In [114]:
train_catagory

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,  0,
        1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19, 20,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15

In [115]:
per_errors

[0.25406873390037404,
 0.2410687214407665,
 0.24626107660331206,
 0.26101685198297714,
 0.26228652242669304,
 0.2733995906230143,
 0.29201047936184,
 0.2994242860282535,
 0.315753478165324,
 0.324566400126461,
 0.33054723642042544,
 0.31970293672242156,
 0.3364319284831305,
 0.334159908560673,
 0.3234603201054376,
 0.34483688589418315,
 0.3509404384206537,
 0.34077256865493344,
 0.3455491706492769,
 0.3378226232487549,
 0.3512100282538429,
 0.41185890258983965,
 0.44300368342205804,
 0.4845311414305459,
 0.5182419262068454,
 0.5498729979597181,
 0.5505939361064427,
 0.5514614660127294]

In [116]:
errors

[1.3968253968253967,
 1.253968253968254,
 1.2989417989417988,
 1.3703703703703705,
 1.3015873015873016,
 1.343915343915344,
 1.3941798941798942,
 1.4285714285714286,
 1.4497354497354498,
 1.492063492063492,
 1.462962962962963,
 1.4550264550264551,
 1.529100529100529,
 1.4947089947089947,
 1.447089947089947,
 1.5264550264550265,
 1.5687830687830688,
 1.552910052910053,
 1.5740740740740742,
 1.5343915343915344,
 1.5555555555555556,
 1.5952380952380953,
 1.619047619047619,
 1.6719576719576719,
 1.6904761904761905,
 1.7513227513227514,
 1.7513227513227514,
 1.687830687830688]